# Horizontal Pod Autoscaler for the camera-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: camera11-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: camera-service-section1-camera1
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

---
# Horizontal Pod Autoscaler for the camera-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: camera12-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: camera21-service-section1-camera2
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

---
# Horizontal Pod Autoscaler for the camera-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: camera21-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: camera-service-section2-camera1
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

---
# Horizontal Pod Autoscaler for the camera-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: camera22-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: camera-service-section2-camera2
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

---
# Horizontal Pod Autoscaler for the collector-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: collector-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: collector-service-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---
# Horizontal Pod Autoscaler for the image-analysis-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: face-recognition-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: face-recognition-service-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---
# Horizontal Pod Autoscaler for the image-analysis-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: image-analysis-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-analysis-service-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---
# Horizontal Pod Autoscaler for the section-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: section1-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: section-service-1
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

---
# Horizontal Pod Autoscaler for the section-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: section2-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: section-service-2
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---
# Horizontal Pod Autoscaler for the alert-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: alert-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alert-service-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80